@ValidateAllTheThings_HostAddress = http://localhost:5031

POST {{ValidateAllTheThings_HostAddress}}/weatherforecast/
Accept: application/json
Content-Type: application/json

{
  "Days": 3,
  "ZipCode": "99999"
}

###

@year=2026
@month=2
@day=29
GET {{ValidateAllTheThings_HostAddress}}/weatherforecast/{{year}}/{{month}}/{{day}}
Accept: application/json

###
